ginlong_data_processing:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_POSTGRES_HOST') }}"
      user: "{{ env_var('DBT_POSTGRES_USER') }}"
      password: "{{ env_var('DBT_POSTGRES_PWD') }}"
      port: 5432
      dbname: "{{ env_var('DBT_POSTGRES_DB') }}"
      schema: dev_schema
      threads: 1
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 60 # default 10 seconds
